// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: button
			/// 2D
			/// </summary>
			public const string button = "button";

			/// <summary>
			/// Tag: Crickets
			/// 3D
			/// </summary>
			public const string Crickets = "Crickets";

			/// <summary>
			/// Tag: Crickets v2
			/// 3D
			/// </summary>
			public const string Crickets_v2 = "Crickets v2";

			/// <summary>
			/// Tag: Environment
			/// 2D
			/// </summary>
			public const string Environment = "Environment";

			/// <summary>
			/// Tag: music
			/// 2D
			/// </summary>
			public const string music = "music";

			/// <summary>
			/// Tag: NewTag
			/// 2D
			/// </summary>
			[System.Obsolete("Cache")]
			public const string NewTag = "NewTag";

			/// <summary>
			/// Tag: nyaffybells
			/// 3D
			/// </summary>
			public const string nyaffybells = "nyaffybells";

			/// <summary>
			/// Tag: nyaffymovement
			/// 2D
			/// </summary>
			public const string nyaffymovement = "nyaffymovement";

			/// <summary>
			/// Tag: panel
			/// 2D
			/// </summary>
			public const string panel = "panel";

			/// <summary>
			/// Tag: player
			/// 2D
			/// </summary>
			public const string player = "player";

			/// <summary>
			/// Tag: recolectable
			/// 2D
			/// </summary>
			public const string recolectable = "recolectable";

			/// <summary>
			/// Tag: sfx
			/// 2D
			/// </summary>
			[System.Obsolete("Cache")]
			public const string sfx = "sfx";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: ambiente
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string ambiente = "ambiente";

			/// <summary>
			/// Variable: buttonstatus
			/// Range: [0 - 2]
			/// Type: Local
			/// </summary>
			public const string buttonstatus = "buttonstatus";

			/// <summary>
			/// Variable: nature
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string nature = "nature";

			/// <summary>
			/// Variable: nyaffymode
			/// Range: [0 - 4]
			/// Type: Local
			/// </summary>
			public const string nyaffymode = "nyaffymode";

			/// <summary>
			/// Variable: panelmode
			/// Range: [0 - 2]
			/// Type: Local
			/// </summary>
			public const string panelmode = "panelmode";

			/// <summary>
			/// Variable: pickup
			/// Range: [0 - 2]
			/// Type: Local
			/// </summary>
			public const string pickup = "pickup";

			/// <summary>
			/// Variable: radar
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string radar = "radar";

			/// <summary>
			/// Variable: steps
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string steps = "steps";

			/// <summary>
			/// Variable: volume_forest
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string volume_forest = "volume_forest";

			/// <summary>
			/// Variable: volume_house
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string volume_house = "volume_house";

			/// <summary>
			/// Variable: volume_music
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string volume_music = "volume_music";

			/// <summary>
			/// Variable: volume_sfx
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string volume_sfx = "volume_sfx";

		}

		public class Channels
		{
			public const string Crickets = "Crickets";

			public const string Master = "Master";

			public const string music = "music";

			public const string nyaffy = "nyaffy";

			public const string panel = "panel";

			public const string player = "player";

			public const string sfx = "sfx";

			public const string Wind = "Wind";

		}
	}
}
